version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
      - name: hosts
      - name: reviews
        loaded_at_field: date::timestamp
        freshness:
          warn_after: {count: 1, period: hour}
          # error_after: {count: 24, period: hour}