version: 2

sources:
  - name: airbnb
    meta:
      external_location: "read_csv_auto('{prefix}{file}')"
      prefix: "../init/data/"
    tables:
      - name: listings
        meta:
          file: "listings.csv"
      - name: hosts
        meta:
          file: "hosts.csv"
      - name: reviews
        meta:
          file: "reviews.csv"
