name: 'airbnb'
version: '1.0.0'
config-version: 2

profile: 'airbnb'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  airbnb:
    # Default materialization is view
    +materialized: view
    src:
      # Staging layer is ephemeral (no references)
      +materialized: ephemeral
    dim:
      # Dimensions default to table (referenced often)
      +materialized: table

data_tests:
  +store_failures: true
  +schema: _test_failures