name: 'airbnb'
version: '1.0.0'
config-version: 2

profile: 'airbnb'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

clean-targets:
  - 'target'
  - 'dbt_packages'

# define hooks
on-run-start:
  - "CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log ( model_name TEXT, run_timestamp TIMESTAMP )"

models:
  airbnb:
    # +grants:
      # select: ["transform", "reporter"]
    +post-hook:
      - "INSERT INTO {{ target.schema }}.audit_log VALUES ('{{ this }}', CURRENT_TIMESTAMP)"
    # Default materialization is view
    +materialized: view
    src:
      # Staging layer is ephemeral (no references)
      +materialized: ephemeral
    dim:
      # Dimensions default to table (referenced often)
      +materialized: table

data_tests:
  +store_failures: true
  +schema: _test_failures
flags:
  require_generic_test_arguments_property: true