# dbt profiles.yml - DuckDB configuration
# Modern local data stack: DuckDB replaces PostgreSQL for faster transformations

airbnb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', 'airbnb.duckdb') }}"
      schema: main
      threads: 4
      plugins:
        - module: delta  # enables reading Delta tables as sources
